// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmY-PbSJNm0x2k4nWENSA2khZYsbf5d84',
    appId: '1:190918956616:web:c7cc92d08f8cde0146aa7d',
    messagingSenderId: '190918956616',
    projectId: 'orya-v3',
    authDomain: 'orya-v3.firebaseapp.com',
    storageBucket: 'orya-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgZb3A_XKM_NFgoPHq0_71DpX1TUo4pQ',
    appId: '1:190918956616:ios:e1cfbd65fe5eb1fa46aa7d',
    messagingSenderId: '190918956616',
    projectId: 'orya-v3',
    storageBucket: 'orya-v3.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgZb3A_XKM_NFgoPHq0_71DpX1TUo4pQ',
    appId: '1:190918956616:ios:e1cfbd65fe5eb1fa46aa7d',
    messagingSenderId: '190918956616',
    projectId: 'orya-v3',
    storageBucket: 'orya-v3.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmY-PbSJNm0x2k4nWENSA2khZYsbf5d84',
    appId: '1:190918956616:web:4b1b2b0f3b2bc0ed46aa7d',
    messagingSenderId: '190918956616',
    projectId: 'orya-v3',
    authDomain: 'orya-v3.firebaseapp.com',
    storageBucket: 'orya-v3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxpVh7vBEi14CKoO1giy4uygCMVZSP-E',
    appId: '1:190918956616:android:8d5d540f2c66ff7b46aa7d',
    messagingSenderId: '190918956616',
    projectId: 'orya-v3',
    storageBucket: 'orya-v3.firebasestorage.app',
  );

}